from adafruit_hid.keycode import Keycode

Codes = {
    "q": Keycode.Q,
    "w": Keycode.W,
    "e": Keycode.E,
    "r": Keycode.R,
    "t": Keycode.T,
    "y": Keycode.Y,
    "u": Keycode.U,
    "i": Keycode.I,
    "o": Keycode.O,
    "p": Keycode.P,
    "a": Keycode.A,
    "s": Keycode.S,
    "d": Keycode.D,
    "f": Keycode.F,
    "g": Keycode.G,
    "h": Keycode.H,
    "j": Keycode.J,
    "k": Keycode.K,
    "l": Keycode.L,
    "z": Keycode.Z,
    "x": Keycode.X,
    "c": Keycode.C,
    "v": Keycode.V,
    "b": Keycode.B,
    "n": Keycode.N,
    "m": Keycode.M,
    " ": Keycode.SPACE,

    "1": Keycode.ONE,
    "2": Keycode.TWO,
    "3": Keycode.THREE,
    "4": Keycode.FOUR,
    "5": Keycode.FIVE,
    "6": Keycode.SIX,
    "7": Keycode.SEVEN,
    "8": Keycode.EIGHT,
    "9": Keycode.NINE,
    "0": Keycode.ZERO,

    "re": Keycode.ENTER,
    "bs": Keycode.BACKSPACE,
    "es": Keycode.ESCAPE,
    "tb": Keycode.TAB,
    "la": Keycode.LEFT_ARROW,
    "ra": Keycode.RIGHT_ARROW,
    "ua": Keycode.UP_ARROW,
    "da": Keycode.DOWN_ARROW,
    "cl": Keycode.CAPS_LOCK,
    "ps": Keycode.PRINT_SCREEN,
    "sl": Keycode.SCROLL_LOCK,
    "br": Keycode.PAUSE,
    "in": Keycode.INSERT,
    "ho": Keycode.HOME,
    "pu": Keycode.PAGE_UP,
    "pd": Keycode.PAGE_DOWN,
    "en": Keycode.END,
    "de": Keycode.DELETE,
    "gu": Keycode.GUI,

    "f1": Keycode.F1,
    "f2": Keycode.F2,
    "f3": Keycode.F3,
    "f4": Keycode.F4,
    "f5": Keycode.F5,
    "f6": Keycode.F6,
    "f7": Keycode.F7,
    "f8": Keycode.F8,
    "f9": Keycode.F9,
    "fa": Keycode.F10,
    "fb": Keycode.F11,
    "fc": Keycode.F12
}
